apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: grafana-vm
  labels:
    kubevirt.io/vm: grafana-vm
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: grafana-vm
        app: grafana
    spec:
      domain:
        resources:
          requests:
            memory: 1024M
            cpu: 1
        devices:
          interfaces:
            - name: default
              masquerade: {}
              ports:
                - name: grafana
                  port: 3000
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: datadisk
              disk:
                bus: virtio
              serial: grafanadata
      networks:
        - name: default
          pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/containerdisks/ubuntu:22.04
        - name: datadisk
          persistentVolumeClaim:
            claimName: grafana-data-pvc
        - name: cloudinitdisk
          cloudInitNoCloud:
            secretRef:
              name: grafana-cloudinit
